### PR TITLE
Uptime refactor

### PR DESCRIPTION
**Pull request by Samoxive**
My initial solution to moving uptime functionality from a dependency to the core program. It is not as pretty as i would hope it would be, this PR is open to any suggestions.

### CODE REVIEW

**Comment by rgoliveira** [comment]
Ok, so I'll have to say you didn't actually refactor the functionality into the core. You're just loading the plugin manually.

My suggestions would be to:
- move the [`getUptime`](https://github.com/rgoliveira/AwesomeBot/commit/90f814663ae3b07a5f2381419ad749fb4e7aab4f#diff-09d7d449414c21fbdbd54d41e6210e6cR14) into the main script, but this may require to move basically the whole plugin code;
- or, and I guess this is easier and more "clean",  just move the [`startTime`](https://github.com/rgoliveira/AwesomeBot/commit/90f814663ae3b07a5f2381419ad749fb4e7aab4f#diff-09d7d449414c21fbdbd54d41e6210e6cR1) to the main script to store its "boot time", this way the plugin will have access to this timestamp and be able to do the calculations the way it needs

**Comment by Samoxive** [comment]
I initially didn't want to move whole uptime code to AwesomeBot.js because of all the constants it introduces to global namespace, so should i add an if condition to AwesomeBot.onMessage() for uptime functionality?

**Comment by rgoliveira** [comment]
Maybe it's better to create a "utils" file. I'd create a directory `./lib` and move this time diff function there. Also, create a `bootTime` (or similar) on the bot and initialize it on the constructor.

This way the uptime plugin and your new plugin can both just call this function.

What do you think?

**Comment by Samoxive** [comment]
Sounds reasonable, will follow it

**Comment by rgoliveira** [comment]
Ok, it took me too much time to review this, so I went and pushed what I intended with my previous comments. See f6fae62 and 0abbf37.

**Pull request closed without merging**
