### PR TITLE
Isolate APIs tokens/keys

### PR DESCRIPTION
**Pull request by rgoliveira**
Based on a tip from @melmsie, it's probably better for us to isolate all the secrets (APIs tokens/keys) in a place safe from accidental commits.

I created a `tokens.json.example` that would have to be copied/renamed to `tokens.json` (which is git-ignored) and then filled with the appropriate keys. This way it's not necessary to mess with `settings.json` and accidentally commit the secrets in it.

Anyone against it or have ideas to improve?

### CODE REVIEW

**Comment by raylu** [comment]
on the one hand, I'm of the opinion that JSON is not a config file format and shouldn't be used to store data at rest (doesn't support comments, is a pain to edit because you have to match braces and get commas just right) and YAML and others are superior. on the other, clearly the npm devs have already made this mistake so that ship has sailed

perhaps consider just having a .js file with an actual js object that is exported so you can have trailing commas, comments, etc.

the general approach to managing config is the exact one I use in my projects though

**Comment by rgoliveira** [comment]
@raylu I see your points about a json not being the ideal format for this, but I disagree. json is "natively" loaded (`require('./tokens.json')`), and any comments on how to set it up should reside on the documentation anyways. Also, this is a file that's updated once to get the bot running, and then only when a key happens to change or needs to be added.

Maybe a yaml is easier to write, but it's really not a big deal for a file that gets so few updates.

**Comment by melmsie** [comment]
woo!

**Comment by Samoxive** [comment]
i am okay with it since you cannot ignore a config file once it is pushed, 👍

**Comment by rgoliveira** [comment]
@Samoxive but I'm not pushing the config file, just an example of it. You'd have to manually copy it with the right name.

I tried pushing the file and then ignoring it, but `git clone` wouldn't download it... If you know how to make this the right way, I'd be happy to do it.

If not, I'll merge

**Comment by rgoliveira** [comment]
@devoidfury watch out: you'll need to move the api keys to the new `tokens.json` on your instance

**Comment by raylu** [comment]
>  json is "natively" loaded (require('./tokens.json'))

I'm not sure what "natively" means here and why that is an argument in favor of JSON. JS files are "natively" loaded too, probably (`require('./tokens.js')`).

> any comments on how to set it up should reside on the documentation anyways.

The comments are often not for how to set it up - config comments are not documentation. Consider
```yaml
cow: moo
dog: moo # can't woof because Jupiter's alignment is wrong this year
```

> Also, this is a file that's updated once to get the bot running, and then only when a key happens to change or needs to be added.

> Maybe a yaml is easier to write, but it's really not a big deal for a file that gets so few updates.

These are arguments for why JSON will be a minor pain instead of a major pain, not reasons for why JSON is suitable for configuration. Why not use a JS file instead?

**Comment by rgoliveira** [comment]
> Why not use a JS file instead?

I don't like the idea of putting configuration data in a file type intended to hold application code. There's really no need to allow people to have so many freedom when all we need is key/value pairs. When you see a JSON, you know this is what you're getting.

And I don't really see the point of having comments inside a configuration file. Your example would be easily explained in the project docs or, if needed, the application would validate some crazy demand (like Jupyter's alignment :stuck_out_tongue:).

I prefer to read and write yaml, as it's way simpler and more visual, but JSON is just easier to load. Any PRs to support other formats are more than welcome, though! :grinning:

**Pull request merged**
