### PR TITLE
Update codeblock.txt

### PR DESCRIPTION
**Pull request by asishm**

### CODE REVIEW

**Comment by devoidfury** [comment]
Yes, they should be escaped

**Comment by asishm** [comment]
Right, they should.

**Comment by devoidfury** [comment]
To show the backticks, they need to be escaped. They're escaped like this:
\\\`\\\`\\\`
escaped example
\\\`\\\`\\\`

Same as they were originally

**Comment by tbodt** [comment]
c'mon, merge already

**Pull request merged**
